export enum colors {
  WHITE = "white",
  WHITE_DARK = "white-dark",
  WHITE_LIGHT = "white-light",
  BLACK = "black",
  BLACK_LIGHT = "black-light",
  BLACK_DARK = "black-dark",
  GRAY = "gray",
  GRAY_DARK = "gray-dark",
  GRAY_LIGHT = "gray-light",
  PRIMARY = "primary",
  PRIMARY_HARD = "primary-hard",
  PRIMARY_DARK = "primary-dark",
  PRIMARY_LIGHT = "primary-light",
}
